version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  run_tests:
    docker: #where things will be ran(docker, windows, mac, virtual machine)
      - image: circleci/node
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          name: Install Back-End Dependencies
          command: npm run backend:install
      - run:
          name: Run Unit Test
          command: |
            npm run test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
workflows:
  build_tests:
    jobs:
      - run_tests
