version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  run_tests:
    docker: #where things will be ran(docker, windows, mac, virtual machine)
      - image: circleci/node
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run:
          name: Run Unit Test
          command: |
            ./node_modules/jasmine/bin/jasmine src/models/tests --reporter jasmine-spec-reporter --reporter-options reportDir=test-results, reportFilename=test-results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
workflows:
  build_tests:
    jobs:
      - run_tests
