version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  run_tests:
    docker: #where things will be ran(docker, windows, mac, virtual machine)
      - image: cimg/base:2023.02
    steps:
      - node/install:
          node-version: 16.15.0
      - checkout #git clone
      - run:
          name: Install NPM Dependencies
          command: |
            npm install -g
      - run:
          name: Install Docker
          command: |
              set -x
              VER="17.03.0-ce"
              curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
              tar -xz -C /tmp -f /tmp/docker-$VER.tgz
              mv /tmp/docker/* /usr/bin
      - run:
          name: Build Docker image
          command: docker build -t rlondon3/auth-user-wci .
workflows:
  build_tests:
    jobs:
      - run_tests
